using MvcApplication2.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MvcApplication2.DataLoad
{
    public class ClouthDataLoader
    {
        public static IEnumerable<Models.Clouth> Data(Guid? type)
        {
            IEnumerable<Models.Clouth> data = null;
            if (type == null)
                return GetAll();
            switch (type.ToString())
            {
                //Antes daba los precios con iva incluido
                case "8f6ecf5a-c8f3-4739-913e-f7c4332aa0c0":
                    data = GetAllXMayorPrecioVenta();
                    break;
                case "b816fa50-7828-4bf8-88d8-1a841c30d51f":
                    //NEGOCIO x-mayor
                    data = GetAllNegocioXMayor();
                    break;

                case "213f2fe3-544e-4449-8257-ef8b6e956b2f":
                    //x-NUBE
                    data = GetAllNube();
                    break;

                case "ef384aad-f07a-48e3-a69e-571671e3c004":
                    //GENERAL
                    data = GetAllGeneral();
                    break;

                case "15c2bc84-b67e-406b-9e0a-0b8330ebbfec":
                    //Local x menor
                    data = GetAllLocal();
                    break;
                case "c0f589e3-ccfd-4367-b3d6-247af4ef28d9":
                    //NEGOCIO x-mayor OLD
                    data = GetAllNegocioXMayorOld();
                    break;

                default:
                    data = GetAll();
                    break;
            }
            return data;
        }

        public static IEnumerable<Models.Clouth> GetAllLocal()
        {
            var list = new List<Models.Clouth>();

            ////10,11 SOLO grris
            ////,09,13,14,,15,16,18,24,25,29,31,33,38,39,41,44,47,48,50,51, 60,66,69,72,

            //var idsListaActualPorMenor = new List<int>()
            //{
            //    8110,8111,8120,8121,8122,8123,8143,8152,8154,8156,8158,8162,8163,8164,8176,8172,8183,8184,8175, 8173,
            //    8102, 8107, 8108,8101, 8136,  8153, 8106, 8126, 8137,8127, 8155
            //    //8102,8107, 8108, 8111,8185,8101,8173, 8136,8153, 8116, 8147,8112, 8106, 8126, 8137, 8127, 8155
            //};
            //var listaActual = GetAllClouthFactory().Where(x=> idsListaActualPorMenor.Contains(x.Id) );
            //list.AddRange(listaActual.Select(x => x.GetPorMenor()));

            //var listLocal = new List<Models.ClouthFactory>();
            //listLocal.Add(new Models.ClouthFactory(8185, "CAMPERA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 8", "$ 498", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 al 8", "$ 798", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7915, "SHORT LISO C MOÑO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 y 2", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 y 2", "", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7914, "MUSCULOSA C/NUDO BEBA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 120,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 160,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7917, "CAMISA PLUMETI", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("2 AL 5", "$ 239,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("2 AL 5", "$ 339,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7921, "SOLERO C/VOLADOS", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1, 3, 4, 5", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1, 3, 4, 5", "$ 289,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7922, "VESTIDO ESTAMPADO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 4", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 4", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7925, "VESTIDO PLUMETI", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 268,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 372,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7926, "VESTIDO C/VOLADO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7933, "BERMUDA JEAN C/RECORTE", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 329,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 490,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7940, "REMERON FLAMENCOS", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("6 AL 14", "$ 159,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("6 AL 14", "$ 209,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7941, "MUSCULOSA ESTAMPADA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 160,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 230,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7944, "ENTERITO ESTAMPADO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 268,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 388,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7946, "VESTIDO C/VOLADO FIBRANA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("12 y 14", "$ 378,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("12 y 14", "$ 567,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7951, "SHORT FIBRANA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("", "$ 186,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("", "$ 246,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7956, "REMERA C/CARTERA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 145,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 218,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7967, " BLUSA FIBRANA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("8 AL 14", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("8 AL 14", "$ 299,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7969, "VESTIDO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("12 y 14", "$ 368,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("12 y 14", "$ 552,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7974, "VESTIDO BODY MINI", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("0 AL 3", "$ 218,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("0 AL 3", "$ 320,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7983, "SOLERO ESTAMPADO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("2, 3 y 5", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("2, 3 y 5", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7985, "REMERA SIN MANGA UNICORNIO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 159,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 225,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7988, "SHORT RUSTICO MINIBEBE", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("2, 3 y 5", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("2, 3 y 5", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7989, "SHORT RUSTICO NENA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 198,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 14", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7990, "MUSCULOSA DE ALGODON", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 8", "$ 95,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 8", "$ 148,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(5010, "CAMISA CON VOLADOS", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1", "$ 299,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1", "$ 299,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7010, "VESTIDO CON MOÑO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 6", "$ 198,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 6", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7060, "MONO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4, 6, 8, 10 y 14", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4, 6, 8, 10 y 14", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7725, "SHORT", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 348,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 520,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7977, "ENTERITO MINI C/MONITO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("0 AL 3", "$ 200,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("0 AL 3", "$ 300,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7481, "MUSCULOSA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("8 AL 14", "$ 100,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("8 AL 14", "$ 150,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7725, "SHORT", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 348,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 5", "$ 520,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7737, "BODY", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 4", "$ 199,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("1 AL 4", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7744, "VESTIDO FLORES", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("6, 8 y 14", "$ 298,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("6, 8 y 14", "$ 398,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7766, "SHORT DE BAÑO", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 8", "$ 198,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("4 AL 8", "$ 298,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7767, "MUSCULOSA 23", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("6 AL 14", "$ 100,00", "", ""), new PriceByList("", "", "", ""), new PriceByList("6 AL 14", "$ 148,00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //listLocal.Add(new Models.ClouthFactory(7961, "REMERA S/MANG", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("8, 10 y 14", "$ 128,00 ", "", ""), new PriceByList(                   "", "", "", ""), new PriceByList("8, 10 y 14", "$ 188,00 ", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));

            //list.AddRange(listLocal.Select(x => x.GetPorMenor()));

            list.AddRange(GetAllClouthFactoryPandemia().Select(x => x.GetPorMenor()));
            //DEBERIA CORREGIR
            return list.OrderByDescending(x => x.Id).ToList();
        }

        private static IEnumerable<Models.ClouthFactory> GetAllClouthFactoryPandemia()
        {
            var listLocal = new List<Models.ClouthFactory>();
            listLocal.Add(new Models.ClouthFactory(33, "Buzo plush", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 328.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 438.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(5167, "Campera jean", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T8 y T10", "$ 658.00", "", ""), new PriceByList("T8 y T10", "", "", ""), new PriceByList("T8 y T10", "$ 988.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(5168, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 649.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 974.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(5170, "Saco cruzado", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T6", "$ 539.00", "", ""), new PriceByList("T6", "", "", ""), new PriceByList("T6", "$ 814.00", "", ""), "Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(5503, "Remeron", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 219.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 329.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(7588, "Campera universitaria", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T3 y T4", "$ 792.00", "", ""), new PriceByList("T3 y T4", "", "", ""), new PriceByList("T3 y T4", "", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(7588, "Campera universitaria", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T3 y T4", "$ 792.00", "", ""), new PriceByList("T3 y T4", "", "", ""), new PriceByList("T3 y T4", "", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "7588_1"));
            listLocal.Add(new Models.ClouthFactory(7604, "Campera rústica", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 328.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 494.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(7863, "Chaleco inflable", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 y T2", "$ 328.00", "", ""), new PriceByList("T1 y T2", "", "", ""), new PriceByList("T1 y T2", "$ 494.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(7695, "campera piel algodón", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 438.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 658.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(7696, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T8", "$ 319.00", "", ""), new PriceByList("T8", "", "", ""), new PriceByList("T8", "$ 494.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(7699, "Campera frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 438.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 659.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(7699, "Campera frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 438.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 659.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(6125, "Campera rústica", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 328.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 494.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(6315, "Enterito abrigo polar", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0", "$ 328.00", "", ""), new PriceByList("T0", "", "", ""), new PriceByList("T0", "$ 494.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(7236, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T2 y T3", "$ 328.00", "", ""), new PriceByList("T2 y T3", "", "", ""), new PriceByList("T2 y T3", "$ 438.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(7287, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0", "$ 328.00", "", ""), new PriceByList("T0", "", "", ""), new PriceByList("T0", "$ 438.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(7598, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4", "$ 869.00", "", ""), new PriceByList("T4", "", "", ""), new PriceByList("T4", "$ 1,304.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(7604, "Campera estampada", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1, T2, T4 y T5", "$ 328.00", "", ""), new PriceByList("T1, T2, T4 y T5", "", "", ""), new PriceByList("T1, T2, T4 y T5", "$ 438.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(7822, "Campera piel larga", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1, T3", "$ 439.00", "", ""), new PriceByList("T1, T3", "", "", ""), new PriceByList("T1, T3", "$ 549.00", "", ""), "Rojo, Azul y Beige", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(7835, "Saco con piel", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 y T5", "$ 539.00", "", ""), new PriceByList("T1 y T5", "", "", ""), new PriceByList("T1 y T5", "$ 759.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(7863, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T2", "$ 328.00", "", ""), new PriceByList("T2", "", "", ""), new PriceByList("T2", "$ 438.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(7878, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0 al T3", "$ 215.00", "", ""), new PriceByList("T0 al T3", "", "", ""), new PriceByList("T0 al T3", "$ 325.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(7697, "Campera frisa super heroe", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 325.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 495.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(7698, "Jardinero", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4", "$ 438.00", "", ""), new PriceByList("T4", "", "", ""), new PriceByList("T4", "", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(7902, "Calza estampada", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al 4", "$ 152.00", "", ""), new PriceByList("T1 al 4", "", "", ""), new PriceByList("T1 al 4", "$ 241.00", "", ""), "Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(7906, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 218.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 325.00", "", ""), "Gris", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(7907, "Calza estampada", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al 14", "$ 197.00", "", ""), new PriceByList("T4 al 14", "", "", ""), new PriceByList("T4 al 14", "$ 318.00", "", ""), "Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(7954, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T10", "$ 197.00", "", ""), new PriceByList("T10", "", "", ""), new PriceByList("T10", "$ 318.00", "", ""), "Turquesa, fucsia y gris", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(7956, "Remera varon", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T8, T10, T14", "$ 240.00", "", ""), new PriceByList("T8, T10, T14", "", "", ""), new PriceByList("T8, T10, T14", "$ 328.00", "", ""), "Blanco con Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8001, "Remera", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1, T2", "$ 218.00", "", ""), new PriceByList("T1, T2", "", "", ""), new PriceByList("T1, T2", "$ 328.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8006, "Buzo gatita", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 394.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 572.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8009, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1, T2 y T3", "$ 328.00", "", ""), new PriceByList("T1, T2 y T3", "", "", ""), new PriceByList("T1, T2 y T3", "$ 438.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8010, "Buzo conejo", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T2", "$ 548.00", "", ""), new PriceByList("T2", "", "", ""), new PriceByList("T2", "$ 657.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8015, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 204.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 314.00", "", ""), "Gris", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8027, "Saco frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 328.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 482.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8027, "Saco frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 328.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 482.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8027_1"));
            listLocal.Add(new Models.ClouthFactory(8028, "Jardinero de jean", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 438.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 658.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8028, "Jardinero de jean", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1", "$ 438.00", "", ""), new PriceByList("T1", "", "", ""), new PriceByList("T1", "$ 658.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8030, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al 14", "$ 251.00", "", ""), new PriceByList("T4 al 14", "", "", ""), new PriceByList("T4 al 14", "$ 328.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8030, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al 14", "$ 251.00", "", ""), new PriceByList("T4 al 14", "", "", ""), new PriceByList("T4 al 14", "$ 328.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8030_1"));
            listLocal.Add(new Models.ClouthFactory(8038, "Buzo oso panda", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T6 y T14", "$ 438.00", "", ""), new PriceByList("T6 y T14", "", "", ""), new PriceByList("T6 y T14", "$ 658.00", "", ""), "Crudo y Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8040, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T12 y T14", "$ 605.00", "", ""), new PriceByList("T12 y T14", "", "", ""), new PriceByList("T12 y T14", "$ 908.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8044, "Campera piel", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T14", "$ 528.00", "", ""), new PriceByList("T4 al T14", "", "", ""), new PriceByList("T4 al T14", "$ 791.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8046, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T14", "$ 273.00", "", ""), new PriceByList("T4 al T14", "", "", ""), new PriceByList("T4 al T14", "$ 410.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8047, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T14", "$ 273.00", "", ""), new PriceByList("T4 al T14", "", "", ""), new PriceByList("T4 al T14", "$ 410.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8051, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T8", "$ 539.00", "", ""), new PriceByList("T8", "", "", ""), new PriceByList("T8", "$ 759.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8052, "CAMPERA FRISA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T14", "$ 649.00", "", ""), new PriceByList("T14", "", "", ""), new PriceByList("T14", "$ 869.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8060, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T3", "$ 935.00", "", ""), new PriceByList("T1 al T3", "", "", ""), new PriceByList("T1 al T3", "$ 1,397.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(8065, "chaleco beba", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 y T4", "$ 374.00", "", ""), new PriceByList("T1 y T4", "", "", ""), new PriceByList("T1 y T4", "$ 561.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8066, "Chaleco", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 y T5", "$ 361.00", "", ""), new PriceByList("T1 y T5", "", "", ""), new PriceByList("T1 y T5", "$ 542.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8066, "Chaleco", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 y T5", "$ 361.00", "", ""), new PriceByList("T1 y T5", "", "", ""), new PriceByList("T1 y T5", "$ 542.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8066_1"));
            listLocal.Add(new Models.ClouthFactory(8067, "Campera combinada", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 759.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 1,089.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8069, "Campera nena", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T14", "$ 1,089.00", "", ""), new PriceByList("T4 al T14", "", "", ""), new PriceByList("T4 al T14", "$ 1,529.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8076, "CAMPERA", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4, T12 Y T14", "$ 528.00", "", ""), new PriceByList("T4, T12 Y T14", "", "", ""), new PriceByList("T4, T12 Y T14", "$ 748.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8077, "Campera camuflada", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1, T2 y T3", "$ 759.00", "", ""), new PriceByList("T1, T2 y T3", "", "", ""), new PriceByList("T1, T2 y T3", "$ 1,089.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8079, "Vestido", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T6, T10, T12 y T14", "$ 539.00", "", ""), new PriceByList("T6, T10, T12 y T14", "", "", ""), new PriceByList("T6, T10, T12 y T14", "$ 759.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8081, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T14", "$ 218.00", "", ""), new PriceByList("T14", "", "", ""), new PriceByList("T14", "$ 328.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8085, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T8, T12 y T14", "$ 273.00", "", ""), new PriceByList("T8, T12 y T14", "", "", ""), new PriceByList("T8, T12 y T14", "$ 383.00", "", ""), "Marino, gris y negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8086, "Campera rayada", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0 al T3", "$ 439.00", "", ""), new PriceByList("T0 al T3", "", "", ""), new PriceByList("T0 al T3", "$ 659.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(8102, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T3 ", "$ 549.00", "", ""), new PriceByList("T1 al T3 ", "", "", ""), new PriceByList("T1 al T3 ", "$ 825.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8104, "Calza", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1, T2 y T3", "$ 174.00", "", ""), new PriceByList("T1, T2 y T3", "", "", ""), new PriceByList("T1, T2 y T3", "$ 263.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8104, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T2, T4, T5", "$ 205.00", "", ""), new PriceByList("T2, T4, T5", "", "", ""), new PriceByList("T2, T4, T5", "$ 307.00", "", ""), "Crudo, Rojo y Azul", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8106, "Pantalon frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 263.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 395.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8106, "Pantalon frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 263.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 395.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8106_1"));
            listLocal.Add(new Models.ClouthFactory(8106, "Pantalon frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 263.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 395.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8106_2"));
            listLocal.Add(new Models.ClouthFactory(8106, "Pantalon frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 263.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 395.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8106_3"));
            listLocal.Add(new Models.ClouthFactory(8106, "Pantalon frisa", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 263.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 395.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8106_4"));
            listLocal.Add(new Models.ClouthFactory(8107, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 444.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 658.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8107, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 444.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 658.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8107_1"));
            listLocal.Add(new Models.ClouthFactory(8108, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 535.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 792.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8111, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T14", "$ 583.00", "", ""), new PriceByList("T4 al T14", "", "", ""), new PriceByList("T4 al T14", "$ 875.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8112, "Pantalón rústico", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T8", "$ 281.00", "T10 al T14", "$ 305.00"), new PriceByList("T4 al T8", "", "T10 al T14", ""), new PriceByList("T4 al T8", "$ 421.00", "T10 al T14", "$ 457.00"), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8113, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T8", "$ 217.00", "T10, T12 y T14", "$ 236.00"), new PriceByList("T8", "", "T10, T12 y T14", ""), new PriceByList("T8", "$ 327.00", "T10, T12 y T14", "$ 346.00"), "Blanco, turquesa, melange y marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8136, "Remera camara", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T14", "$ 208.00", "", ""), new PriceByList("T4 al T14", "", "", ""), new PriceByList("T4 al T14", "$ 306.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8165, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4, T8, T10, T12 y T14", "$ 218.00", "", ""), new PriceByList("T4, T8, T10, T12 y T14", "", "", ""), new PriceByList("T4, T8, T10, T12 y T14", "$ 328.00", "", ""), "Verde", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            listLocal.Add(new Models.ClouthFactory(8201, "Remera manga larga love", new PriceByList("T1 Al T5", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 Al T5", "$ 292.00", "", ""), new PriceByList("T1 Al T5", "", "", ""), new PriceByList("T1 Al T5", "$ 439.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8205, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1, T2, T4, T5", "$ 214.00", "", ""), new PriceByList("T1, T2, T4, T5", "", "", ""), new PriceByList("T1, T2, T4, T5", "$ 321.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8221, "BUZO MICRO", new PriceByList("T1 AL T5", "", "", ""), new PriceByList("T1 Al T5", "", "", ""), new PriceByList("T1 AL T5", "$ 398.00", "", ""), new PriceByList("T1 Al T5", "", "", ""), new PriceByList("T1 Al T5", "$ 703.00", "", ""), "Rojo; Melange; Naranja; Aero", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8223, "CHALECO DE PIEL", new PriceByList("T1 AL T5", "", "", ""), new PriceByList("T1 Al T5", "", "", ""), new PriceByList("T1 AL T5", "$ 448.00", "", ""), new PriceByList("T1 Al T5", "", "", ""), new PriceByList("T1 AL T5", "$ 637.00", "", ""), "Marino; Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8223_1"));
            listLocal.Add(new Models.ClouthFactory(8233, "Calza simil jean", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T4 al T8", "$ 339.00", "T10 al T14", "$ 368.00"), new PriceByList("", "", "", ""), new PriceByList("T4 al T8", "$ 516.00", "T10 al T14", "$ 560.00"), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            listLocal.Add(new Models.ClouthFactory(8256, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0, T1, T2", "$ 329.00", "", ""), new PriceByList("T0, T1, T2", "", "", ""), new PriceByList("T0, T1, T2", "$ 493.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(8258, "ENTERITO PIEL CON OREJAS", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0, T1, T2", "$ 615.00", "", ""), new PriceByList("T0, T1, T2", "", "", ""), new PriceByList("T0, T1, T2", "$ 922.00", "", ""), "Beige y Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(8258, "ENTERITO PIEL CON OREJAS", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0, T1, T2", "$ 615.00", "", ""), new PriceByList("T0, T1, T2", "", "", ""), new PriceByList("T0, T1, T2", "$ 922.00", "", ""), "Beige y Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES, imgName: "8258_2"));
            listLocal.Add(new Models.ClouthFactory(8258, "ENTERITO PIEL CON OREJAS", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0, T1, T2", "$ 615.00", "", ""), new PriceByList("T0, T1, T2", "", "", ""), new PriceByList("T0, T1, T2", "$ 922.00", "", ""), "Beige y Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES, imgName: "8258_1"));
            listLocal.Add(new Models.ClouthFactory(8263, "Campera con moños", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 803.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 1,205.00", "", ""), "Azul y Rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8265, "Campera reversible", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 679.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "$ 1,018.00", "", ""), "varios colores", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            listLocal.Add(new Models.ClouthFactory(8268, "Chaleco", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 y T4", "$ 357.00", "", ""), new PriceByList("T1 y T4", "", "", ""), new PriceByList("T1 y T4", "$ 527.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8268, "Chaleco", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 y T4", "$ 357.00", "", ""), new PriceByList("T1 y T4", "", "", ""), new PriceByList("T1 y T4", "$ 527.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8268_1"));
            listLocal.Add(new Models.ClouthFactory(8272, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T0, T1, T2", "$ 412.00", "", ""), new PriceByList("T0, T1, T2", "", "", ""), new PriceByList("T0, T1, T2", "$ 618.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            listLocal.Add(new Models.ClouthFactory(8275, "Campera", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 AL 5", "$ 535.00", "", ""), new PriceByList("T1 AL 5", "", "", ""), new PriceByList("T1 AL 5", "$ 802.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8275, "Campera", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 AL 5", "$ 535.00", "", ""), new PriceByList("T1 AL 5", "", "", ""), new PriceByList("T1 AL 5", "$ 802.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8275_2"));
            listLocal.Add(new Models.ClouthFactory(8275, "Campera", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 AL 5", "$ 535.00", "", ""), new PriceByList("T1 AL 5", "", "", ""), new PriceByList("T1 AL 5", "$ 802.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8275_3"));
            listLocal.Add(new Models.ClouthFactory(8275, "Campera", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 AL 5", "$ 535.00", "", ""), new PriceByList("T1 AL 5", "", "", ""), new PriceByList("T1 AL 5", "$ 802.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8275_4"));
            listLocal.Add(new Models.ClouthFactory(8299, "Campera estampada con moños", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T1 al T5", "$ 858.00", "", ""), new PriceByList("T1 al T5", "", "", ""), new PriceByList("T1 al T5", "", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            listLocal.Add(new Models.ClouthFactory(8048, "", new PriceByList("", "", "", ""), new PriceByList("", "", "", ""), new PriceByList("T8 ", "$ 438.00", "T10 al T14", "$ 482.00"), new PriceByList("T8 ", "", "T10 al T14", ""), new PriceByList("T8 ", "$ 658.00", "T10 al T14", "$ 714.00"), "Marino y negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            return listLocal;
        }

        private static IEnumerable<Models.ClouthFactory> GetAllClouthFactory()
        {
            var list = new List<ClouthFactory>();
            return GetAllClouthFactoryPandemia();
            //list.Add(new Models.ClouthFactory(8201, "REMERA LOVE", new PriceByList("1 AL 5", "$ 265.00", "", ""), new PriceByList("1 AL 5", "$ 228.00", "", ""), new PriceByList("1 AL 5", "$ 228.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 342.00", "", ""), "Blanco; Fucsia; Gris; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8202, "REMERON COMBINADO", new PriceByList("1 AL 5", "$ 242.00", "", ""), new PriceByList("1 AL 5", "$ 208.00", "", ""), new PriceByList("1 AL 5", "$ 208.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 312.00", "", ""), "Fucsia; Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8203, "REMERON LANILLA LISA", new PriceByList("1 AL 5", "$ 242.00", "", ""), new PriceByList("1 AL 5", "$ 208.00", "", ""), new PriceByList("1 AL 5", "$ 208.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 312.00", "", ""), "Rosa; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8204, "CALZA LISA", new PriceByList("1 AL 5", "$ 223.00", "", ""), new PriceByList("1 AL 5", "$ 191.00", "", ""), new PriceByList("1 AL 5", "$ 191.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 287.00", "", ""), "Fucsia; Gris; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8205, "CALZA SIMIL JEAN", new PriceByList("1 AL 5", "$ 226.00", "", ""), new PriceByList("1 AL 5", "$ 194.00", "", ""), new PriceByList("1 AL 5", "$ 194.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 291.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8206, "CALZA RUSTICA", new PriceByList("1 AL 5", "$ 233.00", "", ""), new PriceByList("1 AL 5", "$ 201.00", "", ""), new PriceByList("1 AL 5", "$ 201.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 301.00", "", ""), "Fucsia; Gris; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8207, "PANTALON FRISA CON PUÑOS", new PriceByList("1 AL 5", "$ 340.00", "", ""), new PriceByList("1 AL 5", "$ 292.00", "", ""), new PriceByList("1 AL 5", "$ 292.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 439.00", "", ""), "Fucsia; Melange; Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8208, "BUZO GATITA TRAPECIO", new PriceByList("1 AL 5", "$ 467.00", "", ""), new PriceByList("1 AL 5", "$ 401.00", "", ""), new PriceByList("1 AL 5", "$ 401.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 602.00", "", ""), "Fucsia; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8209, "BUZO CONEJO CON CAPUCHA", new PriceByList("1 AL 5", "$ 493.00", "", ""), new PriceByList("1 AL 5", "$ 424.00", "", ""), new PriceByList("1 AL 5", "$ 424.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 636.00", "", ""), "Fucsia; Melange; Rosa Viejo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8210, "BUZO PIEL", new PriceByList("1 AL 5", "$ 489.00", "", ""), new PriceByList("1 AL 5", "$ 420.00", "", ""), new PriceByList("1 AL 5", "$ 420.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 631.00", "", ""), "Crudo; Rosa; Fucsia; Camel", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8211, "CAMPERA CON VOLADOS", new PriceByList("1 AL 5", "$ 547.00", "", ""), new PriceByList("1 AL 5", "$ 470.00", "", ""), new PriceByList("1 AL 5", "$ 470.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 705.00", "", ""), "Fucsia; Melange; Rosa Viejo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8212, "CAMPERA PLUSH", new PriceByList("1 AL 5", "$ 619.00", "", ""), new PriceByList("1 AL 5", "$ 533.00", "", ""), new PriceByList("1 AL 5", "$ 533.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 799.00", "", ""), "Rosa Viejo; Fucsia; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8213, "CAMPERA PIEL CORAZON", new PriceByList("1 AL 5", "$ 636.00", "", ""), new PriceByList("1 AL 5", "$ 546.00", "", ""), new PriceByList("1 AL 5", "$ 546.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 820.00", "", ""), "Rosa; Crudo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8214, "SACO DE PIEL", new PriceByList("1 AL 5", "$ 457.00", "", ""), new PriceByList("1 AL 5", "$ 393.00", "", ""), new PriceByList("1 AL 5", "$ 393.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 590.00", "", ""), "Rosa; Crudo; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8215, "VESTIDO JEAN", new PriceByList("1 AL 5", "$ 488.00", "", ""), new PriceByList("1 AL 5", "$ 420.00", "", ""), new PriceByList("1 AL 5", "$ 420.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 630.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8216, "REMERA RUGBY", new PriceByList("1 AL 5", "$ 255.00", "", ""), new PriceByList("1 AL 5", "$ 220.00", "", ""), new PriceByList("1 AL 5", "$ 220.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 330.00", "", ""), "Blaco; Melange; Maiz", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8217, "REMERA MANGA LARGA MANGA CORTA", new PriceByList("1 AL 5", "$ 267.00", "", ""), new PriceByList("1 AL 5", "$ 230.00", "", ""), new PriceByList("1 AL 5", "$ 230.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 345.00", "", ""), "Marino-Melange; Rojo-Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8218, "PANTALON CON PUÑOS", new PriceByList("1 AL 5", "$ 340.00", "", ""), new PriceByList("1 AL 5", "$ 292.00", "", ""), new PriceByList("1 AL 5", "$ 292.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 439.00", "", ""), "Marino; Melange; Topo; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8219, "PANTALON CHUPIN", new PriceByList("1 AL 5", "$ 325.00", "", ""), new PriceByList("1 AL 5", "$ 279.00", "", ""), new PriceByList("1 AL 5", "$ 279.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 419.00", "", ""), "Marino; Melange; Topo; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8220, "PANTALON CON RECORTES", new PriceByList("1 AL 5", "$ 366.00", "", ""), new PriceByList("1 AL 5", "$ 314.00", "", ""), new PriceByList("1 AL 5", "$ 314.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 472.00", "", ""), "Negro-Melange; Marino-Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8221, "BUZO MICRO", new PriceByList("1 AL 5", "$ 421.00", "", ""), new PriceByList("1 AL 5", "$ 362.00", "", ""), new PriceByList("1 AL 5", "$ 362.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 543.00", "", ""), "Rojo; Melange; Naranja; Aero", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8222, "BUZO OSO", new PriceByList("1 AL 5", "$ 526.00", "", ""), new PriceByList("1 AL 5", "$ 452.00", "", ""), new PriceByList("1 AL 5", "$ 452.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 678.00", "", ""), "Negro-Rojo-Melange; Marino-Naranja-Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8223, "CHALECO DE PIEL", new PriceByList("1 AL 5", "$ 388.00", "", ""), new PriceByList("1 AL 5", "$ 305.00", "", ""), new PriceByList("1 AL 5", "$ 305.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 500.00", "", ""), "Marino; Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8224, "CAMPERA OSO", new PriceByList("1 AL 5", "$ 519.00", "", ""), new PriceByList("1 AL 5", "$ 446.00", "", ""), new PriceByList("1 AL 5", "$ 446.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 669.00", "", ""), "Maiz; Rojo; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8225, "CAMPERA COHETE", new PriceByList("1 AL 5", "$ 550.00", "", ""), new PriceByList("1 AL 5", "$ 473.00", "", ""), new PriceByList("1 AL 5", "$ 473.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 709.00", "", ""), "Aero; Melange; Rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8226, "SACO DE FRISA", new PriceByList("1 AL 5", "$ 466.00", "", ""), new PriceByList("1 AL 5", "$ 400.00", "", ""), new PriceByList("1 AL 5", "$ 400.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 601.00", "", ""), "Aero; Melange; Tomate", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8227, "REMERA MANGA ANCHA", new PriceByList("4 AL 8", "$ 244.00", "10 AL 14", "$ 264.00"), new PriceByList("4 AL 8", "$ 210.00", "10 AL 14", "$ 227.00"), new PriceByList("4 AL 8", "$ 210.00", "10 AL 14", "$ 227.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 315.00", "10 AL 14", "$ 341.00"), "Blanco; Melange; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8228, "REMERA PERRITO", new PriceByList("4 AL 8", "$ 290.00", "10 AL 14", "$ 315.00"), new PriceByList("4 AL 8", "$ 250.00", "10 AL 14", "$ 271.00"), new PriceByList("4 AL 8", "$ 250.00", "10 AL 14", "$ 271.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 375.00", "10 AL 14", "$ 406.00"), "Blanco; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8229, "REMERA LANILLA", new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), "Melange; Rosa; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8230, "REMERON ESTAMPADO", new PriceByList("4 AL 8", "$ 283.00", "10 AL 14", "$ 306.00"), new PriceByList("4 AL 8", "$ 243.00", "10 AL 14", "$ 263.00"), new PriceByList("4 AL 8", "$ 243.00", "10 AL 14", "$ 263.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 365.00", "10 AL 14", "$ 395.00"), "Fucsia; Marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8231, "CALZA LISA", new PriceByList("4 AL 8", "$ 319.00", "10 AL 14", "$ 346.00"), new PriceByList("4 AL 8", "$ 275.00", "10 AL 14", "$ 298.00"), new PriceByList("4 AL 8", "$ 275.00", "10 AL 14", "$ 298.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 412.00", "10 AL 14", "$ 447.00"), "Fucsia; Melange; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8232, "CALZA RUSTICA", new PriceByList("4 AL 8", "$ 392.00", "10 AL 14", "$ 425.00"), new PriceByList("4 AL 8", "$ 337.00", "10 AL 14", "$ 365.00"), new PriceByList("4 AL 8", "$ 337.00", "10 AL 14", "$ 365.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 506.00", "10 AL 14", "$ 548.00"), "Fucsia; Melange; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8233, "CALZA SIMIL JEAN", new PriceByList("4 AL 8", "$ 358.00", "10 AL 14", "$ 388.00"), new PriceByList("4 AL 8", "$ 308.00", "10 AL 14", "$ 334.00"), new PriceByList("4 AL 8", "$ 308.00", "10 AL 14", "$ 334.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 462.00", "10 AL 14", "$ 501.00"), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8234, "BUZO COMBINADO", new PriceByList("4 AL 8", "$ 609.00", "10 AL 14", "$ 660.00"), new PriceByList("4 AL 8", "$ 524.00", "10 AL 14", "$ 568.00"), new PriceByList("4 AL 8", "$ 524.00", "10 AL 14", "$ 568.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 786.00", "10 AL 14", "$ 852.00"), "Negro-Fucsia; Negro-Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8235, "BUZO PLUSH CON CAPUCHA", new PriceByList("4 AL 8", "$ 680.00", "10 AL 14", "$ 737.00"), new PriceByList("4 AL 8", "$ 585.00", "10 AL 14", "$ 634.00"), new PriceByList("4 AL 8", "$ 585.00", "10 AL 14", "$ 634.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 878.00", "10 AL 14", "$ 951.00"), "Rosa viejo; Melange; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8236, "BUZO PIEL", new PriceByList("4 AL 8", "$ 626.00", "10 AL 14", "$ 678.00"), new PriceByList("4 AL 8", "$ 538.00", "10 AL 14", "$ 583.00"), new PriceByList("4 AL 8", "$ 538.00", "10 AL 14", "$ 583.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 807.00", "10 AL 14", "$ 874.00"), "Camel; Crudo; Rosa; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8237, "CALZA CON CIERRE", new PriceByList("1 AL 5", "$ 418.00", "", ""), new PriceByList("1 AL 5", "$ 360.00", "", ""), new PriceByList("1 AL 5", "$ 360.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 540.00", "", ""), "Fucsia; Melange; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8238, "CAMPERA CON ESTRELLAS", new PriceByList("4 AL 8", "$ 616.00", "10 AL 14", "$ 667.00"), new PriceByList("4 AL 8", "$ 529.00", "10 AL 14", "$ 574.00"), new PriceByList("4 AL 8", "$ 529.00", "10 AL 14", "$ 574.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 794.00", "10 AL 14", "$ 861.00"), "Fucsia; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8239, "CAMPERA COMBINADA", new PriceByList("4 AL 8", "$ 651.00", "10 AL 14", "$ 705.00"), new PriceByList("4 AL 8", "$ 560.00", "10 AL 14", "$ 606.00"), new PriceByList("4 AL 8", "$ 560.00", "10 AL 14", "$ 606.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 840.00", "10 AL 14", "$ 910.00"), "Fucsia; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            ////list.Add(new Models.ClouthFactory(8240, "CAMPERA PIEL", new PriceByList("4 AL 8", "$ 676.00", "10 AL 14", "$ 732.00"), new PriceByList("4 AL 8", "$ 581.00", "10 AL 14", "$ 630.00"), new PriceByList("4 AL 8", "$ 581.00", "10 AL 14", "$ 630.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 872.00", "10 AL 14", "$ 945.00"), "Camel; Rosa; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8241, "PANTALON BENGALINA", new PriceByList("4 AL 8", "$ 310.00", "10 AL 14", "$ 336.00"), new PriceByList("4 AL 8", "$ 267.00", "10 AL 14", "$ 289.00"), new PriceByList("4 AL 8", "$ 267.00", "10 AL 14", "$ 289.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 400.00", "10 AL 14", "$ 433.00"), "Fucsia; Negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8242, "VESTIDO COMBINADO", new PriceByList("4 AL 8", "$ 583.00", "10 AL 14", "$ 632.00"), new PriceByList("4 AL 8", "$ 501.00", "10 AL 14", "$ 543.00"), new PriceByList("4 AL 8", "$ 501.00", "10 AL 14", "$ 543.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 752.00", "10 AL 14", "$ 815.00"), "Fucsia; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8244, "TAPADO FRISA", new PriceByList("4 AL 8", "$ 865.00", "10 AL 14", "$ 937.00"), new PriceByList("4 AL 8", "$ 744.00", "10 AL 14", "$ 806.00"), new PriceByList("4 AL 8", "$ 744.00", "10 AL 14", "$ 806.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 1,116.00", "10 AL 14", "$ 1,209.00"), "Rojo; Negro; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8245, "CAMPERA PIEL CRUZADA", new PriceByList("4 AL 8", "$ 809.00", "10 AL 14", "$ 877.00"), new PriceByList("4 AL 8", "$ 696.00", "10 AL 14", "$ 754.00"), new PriceByList("4 AL 8", "$ 696.00", "10 AL 14", "$ 754.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 1,044.00", "10 AL 14", "$ 1,131.00"), "Negro; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8246, "REMERA MANGA LARGA MANGA CORTA", new PriceByList("4 AL 8", "$ 325.00", "10 AL 14", "$ 352.00"), new PriceByList("4 AL 8", "$ 280.00", "10 AL 14", "$ 303.00"), new PriceByList("4 AL 8", "$ 280.00", "10 AL 14", "$ 303.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 420.00", "10 AL 14", "$ 455.00"), "Marino-Melange; Negro-Rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8247, "PANTALON", new PriceByList("4 AL 8", "$ 475.00", "10 AL 14", "$ 515.00"), new PriceByList("4 AL 8", "$ 409.00", "10 AL 14", "$ 443.00"), new PriceByList("4 AL 8", "$ 409.00", "10 AL 14", "$ 443.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 613.00", "10 AL 14", "$ 665.00"), "Marino; Negro; Melange; Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8248, "PANTALON CON CIERRES", new PriceByList("4 AL 8", "$ 514.00", "10 AL 14", "$ 557.00"), new PriceByList("4 AL 8", "$ 442.00", "10 AL 14", "$ 479.00"), new PriceByList("4 AL 8", "$ 442.00", "10 AL 14", "$ 479.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 663.00", "10 AL 14", "$ 718.00"), "Marino; Negro; Melange; Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8249, "PANTALON COMBINADO", new PriceByList("4 AL 8", "$ 475.00", "10 AL 14", "$ 515.00"), new PriceByList("4 AL 8", "$ 409.00", "10 AL 14", "$ 443.00"), new PriceByList("4 AL 8", "$ 409.00", "10 AL 14", "$ 443.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 613.00", "10 AL 14", "$ 665.00"), "Negro-Melange; Marino-Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8250, "BUZO CON RECORTES", new PriceByList("4 AL 8", "$ 626.00", "10 AL 14", "$ 679.00"), new PriceByList("4 AL 8", "$ 539.00", "10 AL 14", "$ 584.00"), new PriceByList("4 AL 8", "$ 539.00", "10 AL 14", "$ 584.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 808.00", "10 AL 14", "$ 876.00"), "Negro-Melange; Marino-Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8251, "BUZO CON CIERRE", new PriceByList("4 AL 8", "$ 655.00", "10 AL 14", "$ 710.00"), new PriceByList("4 AL 8", "$ 563.00", "10 AL 14", "$ 610.00"), new PriceByList("4 AL 8", "$ 563.00", "10 AL 14", "$ 610.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 845.00", "10 AL 14", "$ 916.00"), "Marino; Negro; Melange; Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8253, "CAMPERA FRISA", new PriceByList("4 AL 8", "$ 769.00", "10 AL 14", "$ 833.00"), new PriceByList("4 AL 8", "$ 661.00", "10 AL 14", "$ 716.00"), new PriceByList("4 AL 8", "$ 661.00", "10 AL 14", "$ 716.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 992.00", "10 AL 14", "$ 1,074.00"), "Marino; Negro; Melange; Topo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8254, "ENTERITO INTERLOCK ESTAMPADO", new PriceByList("0 AL 2", "$ 349.00", "", ""), new PriceByList("0 AL 2", "$ 300.00", "", ""), new PriceByList("0 AL 2", "$ 300.00", "", ""), new PriceByList("0 AL 2", "", "", ""), new PriceByList("0 AL 2", "$ 451.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8255, "VESTIDO BODY DE LANILLA", new PriceByList("0 AL 3", "$ 397.00", "", ""), new PriceByList("0 AL 3", "$ 341.00", "", ""), new PriceByList("0 AL 3", "$ 341.00", "", ""), new PriceByList("0 AL 3", "", "", ""), new PriceByList("0 AL 3", "$ 512.00", "", ""), "Rosa; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8256, "BUZO PLUSH MINI", new PriceByList("0 AL 3", "$ 418.00", "", ""), new PriceByList("0 AL 3", "$ 359.00", "", ""), new PriceByList("0 AL 3", "$ 359.00", "", ""), new PriceByList("0 AL 3", "", "", ""), new PriceByList("0 AL 3", "$ 539.00", "", ""), "Rosa; Melange", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8257, "PANTALON PLUSH MINI", new PriceByList("0 AL 3", "$ 271.00", "", ""), new PriceByList("0 AL 3", "$ 233.00", "", ""), new PriceByList("0 AL 3", "$ 233.00", "", ""), new PriceByList("0 AL 3", "", "", ""), new PriceByList("0 AL 3", "$ 349.00", "", ""), "Rosa; Melange; Aero", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8258, "ENTERITO PIEL", new PriceByList("0 AL 2", "$ 650.00", "", ""), new PriceByList("0 AL 2", "$ 559.00", "", ""), new PriceByList("0 AL 2", "$ 559.00", "", ""), new PriceByList("0 AL 2", "", "", ""), new PriceByList("0 AL 2", "$ 838.00", "", ""), "Crudo; Rosa; Fucsia; Rojo; Aero", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8259, "BUZO PLUSH ZORRO MINI", new PriceByList("0 AL 3", "$ 480.00", "", ""), new PriceByList("0 AL 3", "$ 413.00", "", ""), new PriceByList("0 AL 3", "$ 413.00", "", ""), new PriceByList("0 AL 3", "", "", ""), new PriceByList("0 AL 3", "$ 619.00", "", ""), "Melange; Aero", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8260, "ENTERITO PLUSH", new PriceByList("0 AL 2", "$ 605.00", "", ""), new PriceByList("0 AL 2", "$ 520.00", "", ""), new PriceByList("0 AL 2", "$ 520.00", "", ""), new PriceByList("0 AL 2", "", "", ""), new PriceByList("0 AL 2", "$ 780.00", "", ""), "Melange; Aero", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8261, "ENTERITO ASTRONAUTA", new PriceByList("1 AL 3", "$ 835.00", "", ""), new PriceByList("1 AL 3", "$ 718.00", "", ""), new PriceByList("1 AL 3", "$ 718.00", "", ""), new PriceByList("1 AL 3", "", "", ""), new PriceByList("1 AL 3", "$ 1,077.00", "", ""), "Rojo; Fucsia; Gris; Marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8263, "TAPADO BEBA LISO", new PriceByList("1 AL 5", "$ 849.00", "", ""), new PriceByList("1 AL 5", "$ 730.00", "", ""), new PriceByList("1 AL 5", "$ 730.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 1,096.00", "", ""), "Rojo; Fucsia; Marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8264, "CAMPERA BEBE", new PriceByList("1 AL 5", "$ 843.00", "", ""), new PriceByList("1 AL 5", "$ 725.00", "", ""), new PriceByList("1 AL 5", "$ 725.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 1,088.00", "", ""), "Marino; Gris; Verde militar", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8265, "CAMPERA REVERSIBLE BEBE", new PriceByList("1 AL 5", "$ 718.00", "", ""), new PriceByList("1 AL 5", "$ 617.00", "", ""), new PriceByList("1 AL 5", "$ 617.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 926.00", "", ""), "Marino; Rojo; Gris; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8266, "CAMPERA NENA", new PriceByList("4 AL 8", "$ 1,033.00", "10 AL 14", "$ 1,119.00"), new PriceByList("4 AL 8", "$ 888.00", "10 AL 14", "$ 962.00"), new PriceByList("4 AL 8", "$ 888.00", "10 AL 14", "$ 962.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 1,332.00", "10 AL 14", "$ 1,443.00"), "Fucsia; Negro; Marino; Gris", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8267, "CAMPERA VARON", new PriceByList("4 AL 8", "$ 1,071.00", "10 AL 14", "$ 1,160.00"), new PriceByList("4 AL 8", "$ 921.00", "10 AL 14", "$ 998.00"), new PriceByList("4 AL 8", "$ 921.00", "10 AL 14", "$ 998.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 1,382.00", "10 AL 14", "$ 1,497.00"), "Gris-Negro; Gris-Marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8268, "CHALECO BEBA", new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "#N/A", "10 AL 14", "#N/A"), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8269, "CHALECO BEBE", new PriceByList("1 AL 5", "$ 455.00", "", ""), new PriceByList("1 AL 5", "$ 391.00", "", ""), new PriceByList("1 AL 5", "$ 391.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 587.00", "", ""), "Marino; Rojo; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8270, "CHALECO NENA", new PriceByList("4 AL 8", "$ 508.00", "10 AL 14", "$ 550.00"), new PriceByList("4 AL 8", "$ 437.00", "10 AL 14", "$ 473.00"), new PriceByList("4 AL 8", "$ 437.00", "10 AL 14", "$ 473.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 655.00", "10 AL 14", "$ 710.00"), "Gris; Fucsia; Negro; Marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8271, "CHALECO VARON", new PriceByList("4 AL 8", "$ 564.00", "10 AL 14", "$ 611.00"), new PriceByList("4 AL 8", "$ 485.00", "10 AL 14", "$ 526.00"), new PriceByList("4 AL 8", "$ 485.00", "10 AL 14", "$ 526.00"), new PriceByList("4 AL 8", "", "10 AL 14", ""), new PriceByList("4 AL 8", "$ 728.00", "10 AL 14", "$ 789.00"), "Gris; Negro; Marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8272, "ENTERITO PLUSH ESTAMPADO", new PriceByList("0 AL 3", "$ 435.00", "", ""), new PriceByList("0 AL 3", "$ 374.00", "", ""), new PriceByList("0 AL 3", "$ 374.00", "", ""), new PriceByList("0 AL 3", "", "", ""), new PriceByList("0 AL 3", "$ 561.00", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            //list.Add(new Models.ClouthFactory(8273, "JUMPER DE COORDEROY", new PriceByList("0 AL 3", "$ 399.00", "", ""), new PriceByList("0 AL 3", "$ 343.00", "", ""), new PriceByList("0 AL 3", "$ 343.00", "", ""), new PriceByList("0 AL 3", "", "", ""), new PriceByList("0 AL 3", "$ 515.00", "", ""), "Rosa viejo; Fucsia", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            ////list.Add(new Models.ClouthFactory(8274, "CAMPERA PIEL OSO", new PriceByList("1 AL 5", "$ 636.00", "", ""), new PriceByList("1 AL 5", "$ 546.00", "", ""), new PriceByList("1 AL 5", "$ 546.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 820.00", "", ""), "Crudo; Aero; Rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            ////list.Add(new Models.ClouthFactory(8275, "CAMPERA PIEL", new PriceByList("1 AL 5", "$ 566.00", "", ""), new PriceByList("1 AL 5", "$ 486.00", "", ""), new PriceByList("1 AL 5", "$ 486.00", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "$ 730.00", "", ""), "Crudo; Aero; Rojo; Rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            ////list.Add(new Models.ClouthFactory(8276, "TAPADO ESTAMPADO", new PriceByList("1 AL 5", "#N/A", "", ""), new PriceByList("1 AL 5", "#N/A", "", ""), new PriceByList("1 AL 5", "#N/A", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "#N/A", "", ""), "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            ////list.Add(new Models.ClouthFactory(8277, "BUZO PIEL LLAMA", new PriceByList("1 AL 5", "#N/A", "", ""), new PriceByList("1 AL 5", "#N/A", "", ""), new PriceByList("1 AL 5", "#N/A", "", ""), new PriceByList("1 AL 5", "", "", ""), new PriceByList("1 AL 5", "#N/A", "", ""), "Crudo; Rosa; Fucsia; Camel", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));

            //return list;
        }

        public static IEnumerable<Clouth> GetAllNegocioXMayorOld()
        {
            var list = new List<Models.Clouth>();

            //list.AddRange(GetAllClouthFactory().Select(x => x.GetNegocio()));
            list.Add(new Models.Clouth(7598, "Tapado con piel", "4 al 14", "$ 620,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            list.Add(new Models.Clouth(8001, "REMERA GATITA BEBA", "1 AL 5", "$ 150,00", "", "", "", "", "Rosa, crudo, blanco", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, action: ""));
            list.Add(new Models.Clouth(8001, "REMERA GATITA BEBA", "1 AL 5", "$ 150,00", "", "", "", "", "Rosa, crudo, blanco", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, action: "", imgName: "8001-1"));
            list.Add(new Models.Clouth(8006, "BUZO CON VOLADO", "1 AL 5", "$ 299,00", "", "", "", "", "Rosa chicle, melange, verde beneton", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            list.Add(new Models.Clouth(8006, "BUZO CON VOLADO", "1 AL 5", "$ 299,00", "", "", "", "", "Rosa chicle, melange, verde beneton", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8006-1"));
            list.Add(new Models.Clouth(8006, "BUZO CON VOLADO", "1 AL 5", "$ 299,00", "", "", "", "", "Rosa chicle, melange, verde beneton", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8006-2"));
            list.Add(new Models.Clouth(8007, "BUZO PIEL", "1 AL 4", "$ 285,00", "", "", "", "", "Crudo, beige, rosa nude, rosa chicle", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            list.Add(new Models.Clouth(8007, "BUZO PIEL", "1 AL 4", "$ 285,00", "", "", "", "", "Crudo, beige, rosa nude, rosa chicle", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8007-1"));
            list.Add(new Models.Clouth(8021, "PANTALON FRIZA CON RECORTE", "1 AL 5", "$ 165,00", "", "", "", "", "Melange, marino, topo, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            list.Add(new Models.Clouth(8021, "PANTALON FRIZA CON RECORTE", "1 AL 5", "$ 165,00", "", "", "", "", "Melange, marino, topo, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8021-1"));
            list.Add(new Models.Clouth(8021, "PANTALON FRIZA CON RECORTE", "1 AL 5", "$ 165,00", "", "", "", "", "Melange, marino, topo, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8021-2"));
            list.Add(new Models.Clouth(8021, "PANTALON FRIZA CON RECORTE", "1 AL 5", "$ 165,00", "", "", "", "", "Melange, marino, topo, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8021-3"));
            list.Add(new Models.Clouth(8021, "PANTALON FRIZA CON RECORTE", "1 AL 5", "$ 165,00", "", "", "", "", "Melange, marino, topo, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8021-4"));
            list.Add(new Models.Clouth(8028, "JARDINERO JEAN", "1 AL 4", "$ 415,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            list.Add(new Models.Clouth(8028, "JARDINERO JEAN", "1 AL 4", "$ 415,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8028-1"));
            list.Add(new Models.Clouth(8030, "REMERA RAYADA", "4 AL 8", "$ 143,00", "10 AL 14", "$ 153,00", "", "", "rayado rojo, rayado bordo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            list.Add(new Models.Clouth(8032, "PANTALON RUSTICO", "4 AL 8", "$ 225,00", "10 AL 14", "$ 238,00", "", "", "melange, fucsia, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            list.Add(new Models.Clouth(8038, "BUZO PIEL", "4 AL 8", "$ 340,00", "10 AL 14", "$ 365,00", "", "", "Crudo, beige, rosa nude, rosa chicle", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            list.Add(new Models.Clouth(8046, "REMERA C/ AURICULARES VARON", "4 AL 8", "$ 185,00", "10 AL 14", "$ 198,00", "", "", "Melange, oxido", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            list.Add(new Models.Clouth(8046, "REMERA C/ AURICULARES VARON", "4 AL 8", "$ 185,00", "10 AL 14", "$ 198,00", "", "", "Melange, oxido", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8046-1"));
            list.Add(new Models.Clouth(8047, "REMERA ESTAMPADA", "4 AL 8", "$ 193,00", "10 AL 14", "$ 203,00", "", "", "Melange, oxido", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            list.Add(new Models.Clouth(8047, "REMERA ESTAMPADA", "4 AL 8", "$ 193,00", "10 AL 14", "$ 203,00", "", "", "Melange, oxido", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8047-1"));
            list.Add(new Models.Clouth(8048, "PANTALON C/ RECORTE", "4 AL 8", "$ 259,00", "10 AL 14", "$ 279,00", "", "", "Negro, topo, melange, marino", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            list.Add(new Models.Clouth(8051, "BUZO SKATE", "2 AL 8", "$ 395,00", "", "", "", "", "Marino, melange, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8051-1"));
            list.Add(new Models.Clouth(8051, "BUZO SKATE", "2 AL 8", "$ 395,00", "", "", "", "", "Marino, melange, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8051-2"));
            list.Add(new Models.Clouth(8051, "BUZO SKATE", "2 AL 8", "$ 395,00", "", "", "", "", "Marino, melange, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8051-3"));
            list.Add(new Models.Clouth(8051, "BUZO SKATE", "2 AL 8", "$ 395,00", "", "", "", "", "Marino, melange, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8051-4"));
            list.Add(new Models.Clouth(8051, "BUZO SKATE", "2 AL 8", "$ 395,00", "", "", "", "", "Marino, melange, negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8051-5"));
            list.Add(new Models.Clouth(8052, "CAMPERA COMBINADA", "4 AL 8", "$ 470,00", "10 AL 14", "$ 505,00", "", "", "Rojo con topo, francia con melange, melange con negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            list.Add(new Models.Clouth(8052, "CAMPERA COMBINADA", "4 AL 8", "$ 470,00", "10 AL 14", "$ 505,00", "", "", "Rojo con topo, francia con melange, melange con negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8052-1"));
            list.Add(new Models.Clouth(8052, "CAMPERA COMBINADA", "4 AL 8", "$ 470,00", "10 AL 14", "$ 505,00", "", "", "Rojo con topo, francia con melange, melange con negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8052-2"));
            list.Add(new Models.Clouth(8052, "CAMPERA COMBINADA", "4 AL 8", "$ 470,00", "10 AL 14", "$ 505,00", "", "", "Rojo con topo, francia con melange, melange con negro", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8052-3"));
            list.Add(new Models.Clouth(8056, "ENTERITO PIEL OSO PANDA", "0 AL 2", "$ 425,00", "", "", "", "", "Beige, rojo, aero", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            list.Add(new Models.Clouth(8060, "ASTRONAUTA BORDADO", "1 AL 3", "$ 610,00", "", "", "", "", "Rojo, gris, aero, rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES));
            list.Add(new Models.Clouth(8060, "ASTRONAUTA BORDADO", "1 AL 3", "$ 610,00", "", "", "", "", "Rojo, gris, aero, rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES, imgName: "8060-1"));
            list.Add(new Models.Clouth(8060, "ASTRONAUTA BORDADO", "1 AL 3", "$ 610,00", "", "", "", "", "Rojo, gris, aero, rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES, imgName: "8060-2"));
            list.Add(new Models.Clouth(8060, "ASTRONAUTA BORDADO", "1 AL 3", "$ 610,00", "", "", "", "", "Rojo, gris, aero, rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES, imgName: "8060-3"));
            list.Add(new Models.Clouth(8060, "ASTRONAUTA BORDADO", "1 AL 3", "$ 610,00", "", "", "", "", "Rojo, gris, aero, rosa", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.MINIBEBES, imgName: "8060-4"));
            list.Add(new Models.Clouth(8065, "CHALECO BEBA OREJAS", "1 AL 5", "$ 399,00", "", "", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            list.Add(new Models.Clouth(8065, "CHALECO BEBA OREJAS", "1 AL 5", "$ 399,00", "", "", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8065-1"));
            list.Add(new Models.Clouth(8065, "CHALECO BEBA OREJAS", "1 AL 5", "$ 399,00", "", "", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS, imgName: "8065-2"));
            list.Add(new Models.Clouth(8067, "CAMPERA BEBE  ", "1 AL 5", "$ 570,00", "", "", "", "", "Fondo azul/gris/rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES));
            list.Add(new Models.Clouth(8067, "CAMPERA BEBE  ", "1 AL 5", "$ 570,00", "", "", "", "", "Fondo azul/gris/rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8067-1"));
            list.Add(new Models.Clouth(8067, "CAMPERA BEBE  ", "1 AL 5", "$ 570,00", "", "", "", "", "Fondo azul/gris/rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8067-2"));
            list.Add(new Models.Clouth(8067, "CAMPERA BEBE  ", "1 AL 5", "$ 570,00", "", "", "", "", "Fondo azul/gris/rojo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBES, imgName: "8067-3"));
            list.Add(new Models.Clouth(8069, "CAMPERA ESTAMPADA", "4 AL 8", "$ 790,00", "10 AL 14", "$ 850,00", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8069-1"));
            list.Add(new Models.Clouth(8069, "CAMPERA ESTAMPADA", "4 AL 8", "$ 790,00", "10 AL 14", "$ 850,00", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8069-2"));
            list.Add(new Models.Clouth(8069, "CAMPERA ESTAMPADA", "4 AL 8", "$ 790,00", "10 AL 14", "$ 850,00", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8069-3"));
            list.Add(new Models.Clouth(8069, "CAMPERA ESTAMPADA", "4 AL 8", "$ 790,00", "10 AL 14", "$ 850,00", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8069-4"));
            list.Add(new Models.Clouth(8069, "CAMPERA ESTAMPADA", "4 AL 8", "$ 790,00", "10 AL 14", "$ 850,00", "", "", "Varios estampados", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8069-5"));
            list.Add(new Models.Clouth(8080, "CAMPERA PIEL CON FOIL", "1 AL 5", "$ 378,00", "", "", "", "", "Fucsia, rosa chicle, crudo", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.BEBAS));
            list.Add(new Models.Clouth(8083, "MEDIA POLERA LISA", "1 AL 5", "$ 98,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            list.Add(new Models.Clouth(8083, "MEDIA POLERA LISA", "1 AL 5", "$ 98,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8083-1"));
            list.Add(new Models.Clouth(8083, "MEDIA POLERA LISA", "1 AL 5", "$ 98,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8083-2"));
            list.Add(new Models.Clouth(8083, "MEDIA POLERA LISA", "1 AL 5", "$ 98,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8083-3"));
            list.Add(new Models.Clouth(8084, "REMERA CON LOL", "1 AL 5", "$ 145,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA));
            list.Add(new Models.Clouth(8084, "REMERA CON LOL", "1 AL 5", "$ 145,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8084-1"));
            list.Add(new Models.Clouth(8084, "REMERA CON LOL", "1 AL 5", "$ 145,00", "", "", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.NENA, imgName: "8084-2"));
            list.Add(new Models.Clouth(8085, "REMERA MANGA LARGA CAMUFLADA", "4 AL 8", "$ 198,00", "10 AL 14", "$ 218,00", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON));
            list.Add(new Models.Clouth(8085, "REMERA MANGA LARGA CAMUFLADA", "4 AL 8", "$ 198,00", "10 AL 14", "$ 218,00", "", "", "", Models.Clouth.SUBCATEGORY.REMERAS, Models.Clouth.CATEGORY.VARON, imgName: "8085-1"));
            return list.OrderBy(x => x.Id);
        }

        /// <summary>
        /// NEGOCIO POR MAYOR
        /// </summary>
        /// <returns></returns>
        public static IEnumerable<Models.Clouth> GetAllNegocioXMayor()
        {
            var list = new List<Models.Clouth>();
            //list.AddRange(GetAllClouthFactory().Select(x => x.GetNegocio()));
            list.AddRange(GetAllClouthFactoryPandemia().Select(x => x.GetNegocio()));
            return list.OrderBy(x => x.Id);
        }

        public static IEnumerable<Models.Clouth> GetAllXMayorPrecioVenta()
        {
            var list = new List<Models.Clouth>();
            list.AddRange(GetAllClouthFactory().Select(x => x.GetListaMayor()));
            return list.OrderBy(x => x.Id);
        }

        public static IEnumerable<Models.Clouth> GetAllGeneral()
        {
            var list = new List<Models.Clouth>();
            return GetAllClouthFactory().Select(x => x.GetGeneral()).OrderBy(x => x.Id);
        }

        public static IEnumerable<Models.Clouth> GetAllNube()
        {
            var list = new List<Models.Clouth>();
            return GetAllClouthFactory().Select(x => x.GetNube()).OrderBy(x => x.Id);
        }

        public static IEnumerable<Models.Clouth> GetAllListaMayor()
        {
            var list = new List<Models.Clouth>();
            return GetAllClouthFactory().Select(x => x.GetListaMayor()).OrderBy(x => x.Id);
        }

        public static IEnumerable<Models.Clouth> GetAllPorMenor()
        {
            var list = new List<Models.Clouth>();
            return GetAllClouthFactory().Select(x => x.GetPorMenor()).OrderBy(x => x.Id);
        }

        public static IEnumerable<Models.Clouth> GetAll()
        {
            var list = new List<Models.Clouth>();
            return GetAllClouthFactory().Select(x => x.GetSinPrecio()).OrderBy(x => x.Id);
        }
    }
}